language: node_js
sudo: required
services:
- docker
addons:
  ssh_known_hosts:
  - fiksu.codecontrol.fi
node_js:
- 11.10.0
before_install:
- chmod a+x deploy.sh
- chmod a+x docker_push.sh
- openssl aes-256-cbc -K $encrypted_53365c26be73_key -iv $encrypted_53365c26be73_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- cd $TRAVIS_BUILD_DIR/frontend && npm install
- cd $TRAVIS_BUILD_DIR/backend && npm install
script:
- echo "skipping tests for now"
after_success:
- cd $TRAVIS_BUILD_DIR/frontend && docker build -t codecontrol/fiksu-frontend:dev-"$TRAVIS_BUILD_NUMBER"
  . --label "version=$TRAVIS_BUILD_NUMBER" --label "commitMessage=$TRAVIS_COMMIT_MESSAGE"
  --label "commit=$TRAVIS_COMMIT"
- cd $TRAVIS_BUILD_DIR/backend && docker build -t codecontrol/fiksu-backend:dev-"$TRAVIS_BUILD_NUMBER"
  . --label "version=$TRAVIS_BUILD_NUMBER" --label "commitMessage=$TRAVIS_COMMIT_MESSAGE"
  --label "commit=$TRAVIS_COMMIT"
- cd $TRAVIS_BUILD_DIR && ./docker_push.sh
deploy:
- provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
